# Copyright (C) 2025 iolaire mcfadden.
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Nginx reverse proxy service for Vedfolnir Docker Compose deployment

version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: vedfolnir_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Status endpoint
    volumes:
      # Nginx configuration
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx/nginx_status.conf:/etc/nginx/conf.d/nginx_status.conf:ro
      
      # SSL certificates
      - ./ssl/certs:/etc/nginx/ssl/certs:ro
      - ./ssl/keys:/etc/nginx/ssl/keys:ro
      
      # Static files from application
      - ./static:/app/static:ro
      - ./admin/static:/app/admin/static:ro
      
      # Logs
      - ./logs/nginx:/var/log/nginx
    networks:
      - vedfolnir_external
      - vedfolnir_internal
    depends_on:
      - vedfolnir
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - TZ=UTC
    labels:
      - "traefik.enable=false"
      - "com.vedfolnir.service=nginx"
      - "com.vedfolnir.description=Reverse proxy and load balancer"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  vedfolnir_external:
    external: true
  vedfolnir_internal:
    external: true